"""
Módulo con los textos para generar el informe del test Raven Matrices
"""

# ============================================================================
# PÁRRAFOS FIJOS (siempre se incluyen)
# ============================================================================

PARRAFOS_FIJOS = {

    'titulo_general_prueba': """1. Objetivo de la prueba.""",
    'objetivo_prueba': """La prueba Stroop (Tarea de Interferencia Palabra-Color) es una prueba de evaluación cognitiva, principalmente atencional, que mide velocidad de procesamiento, flexibilidad cognitiva y control inhibitorio. Esto es, mide la capacidad de suprimir respuestas automáticas en favor de respuestas controladas.
    """,


    'titulo_procedimiento': """2. Descripción de la tarea.""",
    'descripcion_procedimiento1': """Durante esta tarea el participante debe nombrar en voz alta, lo más rápido posible y sin equivocarse, una lista de nombres de tres colores: rojo, verde y azul. La prueba consta de tres partes. En la primera parte, Palabras (P), se introduce la lista de colores como una lista de repeticiones de los nombres de estos tres colores escritos en letra negra, tal y como se ve en este extracto de la tarea página 1:""",
    'descripcion_procedimiento2': """En la segunda parte de la prueba, Colores (C) la lista de nombre de colores a recitar en voz alta se introduce como conjuntos de cuatro letras ‘X’, XXXX, de uno de los tres colores posibles, tal y como se muestra en el siguiente extracto de la tarea página 2:""",
    'descripcion_procedimiento3': """Finalmente, en la tercera parte de la prueba, Palabras-Colores (PC), se presenta una lista de repeticiones de los nombres de los tres colores, pero esta vez coloreados por uno de estos tres colores, el cual puede ser congruente o engañoso respecto con el color que textualmente se menciona. El participante tiene en este caso que ignorar el nombre citado textualmente y recitar en voz alta los colores de la lista de elementos que se presenta. Esta lista de la página 3 se ve tal que así:""",


    'titulo_indices': """
    3. Índices que se obtienen.""",
    'descripcion_indices': """De esta prueba se obtienen 3 puntuaciones indicadores de la velocidad de procesamiento del evaluado.
    •P es el número de elementos procesados (palabras leídas correctamente) en la primera página 
    • C es el número de elementos procesados (colores identificados correctamente) recitados en la 2da página.
    • PC es el número de elementos procesados (colores identificados correctamente) en la tercera página.
    • Finalmente, otra puntuación que se obtiene para cada parte de la prueba es el número de errores (E), veces en las que se nombra un color diferente al que corresponde en la lista.
    
Por último, a partir de estas puntuaciones se obtiene una puntuación compuesta:
    • El índice de resistencia a la interferencia (INT). Sirve para señalar individuos con bajo, normal o alto potencial de flexibilidad cognitiva, adaptación al estrés cognitivo y creatividad. Este índice se calcula a partir de la siguiente fórmula: INT = PC-PC' (puntuación esperada en PC) = PC- CxP /C+P
     """,
    
    'titulo_resultados': "Presentación de los resultados de {nombre_completo}",
    
    'texto_tabla_resultados': """En la siguiente tabla se muestra los resultados de {nombre} en la prueba Stroop. Estos resultados se presentan como puntuación directa (PD) y como puntuación típica (PT). La puntuación típica es una calificación que compara la puntuación de {nombre} con la puntuación promedio y desviación típica de puntuaciones que los individuos de su edad tienden a obtener. La desviación típica representa con cuanta variabilidad los participantes de esta prueba puntúan por arriba o por debajo de la puntuación media. En pruebas como esta, en las que se espera una distribución normal de las puntuaciones, esta PT coincide en mayor medida con los percentiles, de manera que un PT de 50 equivaldría a un rendimiento en la prueba superior al 50% de los individuos de su edad, y lo mismo con un PT de 20 o 80 (valor mínimo y máximo respectivamente). Dicho esto, se muestra en la siguiente tabla los resultados obtenidos por {nombre} en esta prueba Stroop:
    """,
}

# ============================================================================
# PÁRRAFOS CONDICIONALES SEGÚN PUNTUACIONES
# ============================================================================

# PD_Total - Según puntuación directa total y correspondiente percentil
PARRAFOS_PT = {

    'P, C y PC bajo ': """{nombre} obtuvo puntuaciones bajas en todas las partes de la prueba. El bajo rendimiento de {nombre} puede estar relacionado con problemas de pronunciación durante la lectura, lo que sugieren la existencia de problemas motores en el habla. Otra explicación del bajo rendimiento puede ser la presencia de elevada perseveración, que es la repetición ralentizadora de una misma respuesta. Debido a alguna de estas dos causas la velocidad de procesamiento de la información de {nombre} es más lenta de lo normal.""",
    
    'P y C bajo y PC normal':"""{nombre} obtuvo puntuaciones bajas en casi toda la prueba, salvo en la parte de palabras-colores, donde su rendimiento fue normal. Este patrón de resultados puede estar asociado a dificultades en la lectura. O, incluso con más probabilidad, a dificultades en la pronunciación, ralentizando así la velocidad con la que {nombre} procesa la información.""",

    'P y C bajo y PC alto ':"""{nombre} obtuvo puntuaciones bajas en casi toda la prueba, salvo en la parte de palabras-colores, donde su rendimiento fue alto, por encima del promedio para su edad. Este patrón de resultados puede estar asociado a dificultades en la lectura o de la pronunciación, lo que ralentizan la velocidad con la que {nombre} procesa la información. Existe una reducida posibilidad de presencia de dislexia pura, es decir, una deficiencia o incapacidad para leer. Esto se infiere del hecho de que esta incapacidad favorecería el alto rendimiento obtenido en palabras-colores mientras que explicaría la baja puntuación en palabras.""",

    'P bajo, C normal y PC bajo ':"""{nombre} obtuvo una puntuación baja en P, una puntuación normal en C y una puntuación baja en PC. Este patrón de resultados puede estar asociado a dificultades en la lectura, lo cual ralentiza la velocidad de procesamiento de la información.""", 

    'P bajo, C y PC normal ':"""{nombre} obtuvo una puntuación baja en P, y un rendimiento normal en C y PC. Este patrón de resultados puede estar asociado a dificultades en la lectura, lo cual ralentiza la velocidad de procesamiento de la información en la parte de lectura de palabras. Mientras que no afecta en la parte de lectura de colores, e incluso facilita la tarea de Palabras-Colores, mejorando así el rendimiento en esta parte.""",
 
    'P bajo, C normal y PC alto ': """{nombre} obtuvo una puntuación baja en P, normal en Colores y superior en Palabras-Colores. Estos resultados señalan que {nombre} probablemente presenta dislexia pura, es decir, una deficiencia o incapacidad para leer. Esta deficiencia explicaría la baja puntuación en palabras, mientras que favorecería el alto rendimiento obtenido en palabras-colores al sufrir menos interferencia atencional por la lectura automatizada de las palabras.""",

    'P bajo, C alto y PC bajo ':"""{nombre} obtuvo puntuaciones bajas en P y PC, y superior al promedio en Colores. Esto es, la velocidad con la que {nombre} procesa la información resulta muy variable en función de si está a analizar información verbal (texto) o no verbal (imágenes). {nombre} presentó un buen foco atencional al procesar los Colores, pero su atención empeoró ante la exposición de palabras. Es interesante en este sentido considerar el aspecto emocional y motivacional de {nombre} ante pruebas verbales. Ya que en algunos casos como este, el menor rendimiento ante pruebas con procesamiento de texto escrito, no se debe tanto a la dificultad lectora, pero a una percepción de autoeficacia negativa, caracterizada por presentar dudas sobre las propias capacidades lectoras.""",

    'P bajo, C alto y PC normal ':"""{nombre} obtuvo una puntuación bajas en P, normal en PC, y superior al promedio en Colores. La velocidad de procesamiento o el foco atencional fue muy bueno al procesar colores, pero empeoró drásticamente ante la exposición de palabras. Este resultado sugieren que {nombre} podría presentar una dislexia leve, es decir, una deficiencia o incapacidad para leer. Aunque una explicación más probable, dada la falta de facilitación evidente en Palabras-Colores, es que: el deterioro en el procesamiento o atención de {nombre} durante la prueba, se debe no tanto a la dificultad lectora, pero a una percepción de autoeficacia negativa, caracterizada por presentar dudas sobre las propias capacidades lectoras. Se recomieda para este caso evaluar como {nombre} se siente emocional y motivacionalmente al tener que realizar una prueba verbal.""",
    
    'P bajo, C y PC alto ': """{nombre} obtuvo un rendimiento bajo en P, y superior al promedio en Colores y Palabras-Colores. Estos resultados indican que {nombre} posiblemente presente una dislexia pura, es decir, una deficiencia o incapacidad para leer. Esta deficiencia explicaría la baja puntuación en palabras, mientras que favorecería el alto rendimiento obtenido en palabras-colores al sufrir menos interferencia atencional por la lectura automatizada de las palabras. Por otro lado, es remarcable la velocidad de procesamiento de {nombre}, que resulta superior al promedio para analizar información no verbal, como en este caso al tener que identificar colores.""",

    'P normal, C y PC bajo ':"""{nombre} obtuvo una puntuación normal en P y puntuaciones bajas en C y PC. Este patrón suele asociarse a la incapacidad para clasificar las claves de color. Esto puede deberse a problemas perceptivos como por ejemplo el daltonismo (incapacidad de distinguir adecuadamente algunos colores, frecuentemente el rojo, verde o azul). Otra explicación menos probable vendría de la incapacidad para citar verbalmente los colores.""", 

    'P normal, C bajo y PC normal ':"""{nombre} obtuvo una puntuación normal en P y PC pero baja en C. {nombre} mantiene una velocidad de lectura promedio para su edad, y también para el procesamiento de la información en general, aunque con un leve deterioro a la hora de identificar claves de color. Este peor rendimiento ante la prueba de Colores también podría explicarse por una deficiencia, puntual de esta parte de la prueba, en la atención sostenida (capacidad para mantener la concentración durante más tiempo).""",

    'P normal, C bajo y PC alto':"""{nombre} obtuvo una puntuación normal en P, baja en C y alta en PC. El rendimiento de {nombre} durante la prueba resultó inestable pero sin seguir un patrón evidente de facilitación dependiente de las demandas de la prueba. {nombre} parece tener una velocidad de lectura de procesamiento adecuada, que incluso supera al promedio al enfrentarse a tareas de mayor dificultad que demandan una mayor atención y un mayor control inhibitorio de la información distractora. Sin embargo, ante tareas más sencillas como en la identificación de claves de color (prueba C), el rendimiento de {nombre} empeora. Una posible explicación a esto puede ser un deterioro en la atención debido a la falta de motivación para ejecutar tareas que se perciben como aburridas o poco estimuladoras.""",

    'P y C normal y PC bajo ':"""{nombre} obtuvo una puntuación normal en P y C y una puntuación baja. Esto indica que {nombre} procesa la información a una velocidad adecuada, pero que esta velocidad se reduce más de lo esperado ante tareas más difíciles o demandantes de una mayor concentración.""",

    'P, C y PC normales' : """{nombre} obtuvo una puntuación normal en todas las partes de la prueba. Esto indica una velocidad de procesamiento y una capacidad atencional adecuada o promedio.""",

    'P y C normal y PC alto':"""{nombre} mostró un rendimiento adecuado en la mayor parte de la prueba, con excepción a una puntuación en la tarea PC por encima del promedio para su edad. Esto indica que {nombre} presenta una velocidad de procesamiento adecuada o promedio acompañada de una atención sobresaliente.""",

    'P normal, C alto y PC bajo ':"""{nombre} mostró un rendimiento normal en P, alto en C, y bajo PC. {nombre} presenta una velocidad de procesamiento adecuada para la lectura, e incluso superior al promedio cuando analiza información no verbal (imágenes). Sin embargo, {nombre} presenta un importante deterioro atencional que le hace rendir peor que la mayoría de individuos de su edad ante tareas de mayor dificultad y demanda atencional.""",

    'P normal, C alto y PC normal ':"""{nombre} obtuvo una puntuación normal en todas las partes de la prueba, con excepción a un rendimiento  en la prueba C por encima del promedio para su edad. Esto indica que {nombre} presenta, por lo general, una velocidad de procesamiento y un capacidad atencional adecuada e igual a la de la mayoría de individuos de su edad. Además, {nombre} presenta una mayor facilidad para la identificación de claves de color, lo que le lleva a rendir por encima del promedio ante tareas sencillas de este tipo.""",

    'P normal, C y PC alto ':"""{nombre} obtuvo una puntuación normal en P y un rendimiento sobresaliente en las pruebas C y PC. Esto indica que {nombre} presenta, una velocidad de procesamiento y un capacidad atencional adecuada para la lectura, igual a la de la mayoría de individuos de su edad. Además, {nombre} presenta una especial facilidad para procesar información no verbal, lo que le lleva a rendir mejor ante tareas de este tipo, con una velocidad de procesamiento y atención por encima del promedio.""",

    'P alto y C y PC bajo ':"""{nombre} mostró un rendimiento sobresaliente en P, pero bajo en C y PC. Para leer, resulta destacable su velocidad de procesamiento por encima del promedio para su edad. Por otro lado, {nombre} también parece presentar una evidente incapacidad para clasificar las claves de color. Esto puede deberse a problemas perceptivos como por ejemplo el daltonismo (incapacidad de distinguir adecuadamente algunos colores, frecuentemente el rojo, verde o azul). Otra explicación menos probable vendría de la incapacidad para citar verbalmente los colores.""",

    'P alto y C bajo y PC normal ':"""{nombre} mostró un rendimiento sobresaliente en P, bajo en C y normal PC. Para leer, resulta destacable su velocidad de procesamiento por encima del promedio para su edad. Por otro lado, en relación a la baja puntuación en C, {nombre} parece presentar mayor dificultad al procesar las claves de color, como por ejemplo podría ser un ligero grado el daltonismo. Aunque dado el rendimiento normal en la parte PC, resulta más probable pensar en una deficiencia puntual en la atención sostenida (capacidad para mantener la concentración durante más tiempo) durante la parte C de la prueba.""",

    'P alto y C bajo y PC alto ':"""{nombre} mostró un rendimiento sobresaliente en P y PC pero bajo en C. Para leer, resulta destacable su velocidad de procesamiento por encima del promedio para su edad. Por otro lado, la atención de {nombre} resulta inestable, afectando drásticamente a su rendimiento durante la prueba. Durante una tarea de mayor complejidad y demanda atencional, {nombre} es capaz de mostrar, tal y como se explica a continuación, una atención discriminativa por encima del promedio. Sin embargo, ante una tarea más sencilla como en la identificación de claves de color (prueba C), el rendimiento de {nombre} empeora. Una posible explicación a esto puede ser un deterioro en la atención sostenida (capacidad para mantener la concentración durante más tiempo) debido a la falta de motivación para ejecutar tareas que se perciben como aburridas o poco estimuladoras.""",
 
    'P alto y C normal y PC bajo ':"""{nombre} obtuvo una puntuación alta en P, normal en C y baja en PC. Esto indica que, al leer texto, {nombre} procesa la información a una velocidad sobresaliente, por encima del promedio para su edad. Pero que esta velocidad se reduce al procesar estímulos no verbales (claves de color). Y reduciéndose incluso más de lo normal ante  tareas más difíciles o demandantes de una mayor concentración. Este peor rendimiento ante la tarea PC puede deberse a un hábito muy automatizado de lectura, que durante esta tarea dificulta la inhibición de la información distractora (los nombres de los colores escritos) y la atención al estímulo relevante (el color de las palabras).""",

    'P alto y C y PC normal':"""{nombre} mostró un rendimiento adecuado a lo largo de toda la prueba. Incluso, superior al promedio en la parte de lectura, destacando su rápida velocidad de procesamiento de información verbal simple.""",

    'P alto y C normal y PC alto ':"""{nombre} mostró un rendimiento sobresaliente en P y PC, y normal en C. Estos resultados señalan una velocidad de procesamiento de la información por encima del promedio para su edad. Este es especialmente notable ante tareas que implican lecturas de texto sencillo. Aunque también resulta sobresaliente el rendimiento de {nombre} ante una tarea de mayor complejidad y demanda atencional.""",
 
    'P y C alto y PC bajo ':"""{nombre} mostró un rendimiento alto en P y C, pero bajo en PC. {nombre} presenta una velocidad de procesamiento sobresaliente, incluso por encima del promedio para su edad, tanto para la lectura como para el procesamiento de claves de colores. Sin embargo, {nombre} presenta un importante deterioro atencional, que le hace rendir peor que la mayoría de individuos de su edad ante tareas de mayor dificultad y demanda atencional.""",

    'P C alto y PC normal ':"""{nombre} mostró un rendimiento sobresaliente en P y C, y normal en PC. Estos resultados señalan una velocidad de procesamiento de la información por encima del promedio para su edad. Este es especialmente notable ante tareas que implican lecturas de texto sencillo, y clasificación de claves no verbales (color). Aunque también resulta adecuado el rendimiento de {nombre} ante una tarea de mayor complejidad y demanda atencional.""",

    'P, C y PC alto ':"""{nombre} mostró un rendimiento sobresaliente en todas las partes de la prueba. Estos resultados señalan una velocidad de procesamiento de la información por encima del promedio para su edad. Este es notable ante tareas que implican lecturas de texto sencillo, clasificación de claves no verbales (color), y también, tareas de mayor complejidad y demanda atencional.""",

}

# ERRORES - errores de comisión, y INT - Interferencia Stroop
TEXTO_ERROR_y_INT= {

'E y INT bajo': """ Otro índice relevante a considerar es el número de errores cometidos por {nombre} durante la prueba. En este sentido, {nombre} cometió pocos errores, lo cual cabe considerar en conjunto con el resto de índices atencionales de la prueba. Aunque en este caso, este índice nos sugiere una baja impulsividad de {nombre} en su respuesta y una sobresaliente capacidad para mantener la concentración durante la mayor parte de la tarea. Por último, en base a la baja puntuación en Interferencia, parece que {nombre} tiene una capacidad atencional selectiva por encima del promedio. Esto es, en su capacidad para inhibir la información distractora, y concentrarse más en la información relevante.""",
'E bajo y INT normal': """ Otro índice relevante a considerar es el número de errores cometidos por {nombre} durante la prueba. En este sentido, {nombre} cometió pocos errores. Esto nos indica una baja impulsividad de {nombre} en su respuesta y una capacidad adecuada para mantener la atención y concentración durante la mayor parte de la tarea. Por último, en base a la puntuación normal en Interferencia, parece que {nombre} es también capaz de controlar esta atención adecuadamente, y voluntariamente inhibir la información distractora y concentrarse más en la información relevante.""",
'E bajo y INT alto': """ Otro índice relevante a considerar es el número de errores cometidos por {nombre} durante la prueba. En este sentido, {nombre} cometió pocos errores. Esto nos indica una baja impulsividad de {nombre} en su respuesta, incluso por debajo del promedio de su edad. Por último, en base a la alta puntuación en Interferencia, parece que {nombre} presenta, sin embargo, cierto deterioro atencional, basado en la dificultad para controlar su atención y voluntariamente inhibir la información distractora y concentrarse más en la información relevante.""",

'E normal y INT bajo':""" En cuanto al número de errores cometidos por {nombre} durante la prueba, este se encuentra dentro de los límites normales. Este índice debe ser considerado en conjunto con el resto de índices atencionales de la prueba. Aunque en este caso, nos está a sugirir que {nombre} no presenta dificultades atencionales para controlar la impulsividad en su respuesta o con la capacidad para mantener la atención durante la tarea. Por último, en base a la baja puntuación en Interferencia, parece que {nombre} tiene una capacidad atencional selectiva por encima del promedio. Esto es, en su capacidad para inhibir la información distractora, y concentrarse más en la información relevante.""",
'E normal y INT normal':""" En cuanto al número de errores cometidos por {nombre} durante la prueba, este se encuentra dentro de los límites normales. Esto nos indica que {nombre} no presenta dificultades atencionales para controlar la impulsividad en su respuesta o para mantener la concentración durante la tarea. Por último, en base a la puntuación normal en Interferencia, parece que {nombre} es también capaz de controlar esta atención adecuadamente, y voluntariamente inhibir la información distractora y concentrarse más en la información relevante.""",
'E normal y INT alto':""" En cuanto al número de errores cometidos por {nombre} durante la prueba, este se encuentra dentro de los límites normales. Este índice debe ser considerado en conjunto con el resto de índices atencionales de la prueba. Aunque en este caso, nos está a sugirir que {nombre} no presenta dificultades atencionales para controlar la impulsividad en su respuesta. Por último, en base a la alta puntuación en Interferencia, parece que {nombre} si que presenta, sin embargo, cierto deterioro atencional, basado en la dificultad para controlar su atención y voluntariamente inhibir la información distractora y concentrarse más en la información relevante.""",

'E alto y INT bajo': """ Otro índice relevante a considerar es el número de errores cometidos por {nombre} durante la prueba. En este sentido, {nombre} cometió un número elevado de errores. Esto señala una excesiva y perjudicial impulsividad de {nombre} en su respuesta, por encima del promedio para su edad. Puede ser recomendable en este aspecto que {nombre} entrene el pensar detenidamente en su respuesta antes de contestar. Por último, respecto a la baja puntuación en Interferencia, parece que {nombre} tiene, sin embargo, una capacidad atencional selectiva por encima del promedio. Esto es, una excelente capacidad para inhibir la información distractora, y concentrarse más en la información relevante.""",
'E alto y INT normal': """ Otro índice relevante a considerar es el número de errores cometidos por {nombre} durante la prueba. En este sentido, {nombre} cometió un número elevado de errores. Esto nos indica una excesiva y perjudicial impulsividad de {nombre} en su respuesta, por encima del promedio para su edad. Puede ser recomendable en este aspecto que {nombre} entrene el pensar detenidamente en su respuesta antes de contestar. Por último, en base a la puntuación normal en Interferencia, parece que {nombre} sí que es, por otro lado, capaz de controlar su atención adecuadamente, y voluntariamente inhibir la información distractora y concentrarse más en la información relevante.""",
'E alto y INT alto': """ Otro índice relevante a considerar es el número de errores cometidos por {nombre} durante la prueba. En este sentido, {nombre} cometió un número elevado de errores. Esto nos indica una excesiva y perjudicial impulsividad de {nombre} en su respuesta, por encima del promedio para su edad. Puede ser recomendable en este aspecto que {nombre} entrene el pensar detenidamente en su respuesta antes de contestar. Este elevado número de errores cometidos también se puede deber a cierta dificultad para mantener la concentración durante toda la tarea. Por último, en base a la alta puntuación en Interferencia, ciertamente parece que {nombre} presenta un deterioro atencional, basado en una deficiencia en su control inhibitorio. Esto es, una incapacidad para controlar su atención y voluntariamente inhibir la información distractora y concentrarse más en la información relevante.""",
}

# Frase final respecto a la interpretación sesgada de la capacidad atencional debido a dislexia
TEXTO_FINAL_PosibleDislexia = {
    'P bajo, C normal y PC normal': """ Finalmente, señalar que debe considerarse con cautela esta interpretación de la velocidad de procesamiento y capacidad atencional de {nombre} en base a su rendimiento en las distintas partes de la tarea Stroop. Esto debido a que existen indicios de que {nombre} puede presentar dislexia. De ser este el caso, el resultado en la evaluación cognitiva de esta prueba verbal estaría sesgado. Por lo que se recomienda para la evaluación cognitiva de {nombre} realizar, en primer lugar, una prueba específica de dislexia. Y para la medición de otras capacidades tales como atención, velocidad de procesamiento o memoria, recurrir a pruebas no verbales.""",
    'P bajo, C normal y PC alto': """ Finalmente, señalar que debe considerarse con cautela esta interpretación de la velocidad de procesamiento y capacidad atencional de {nombre} en base a su rendimiento en las distintas partes de la tarea Stroop. Esto debido a que existen indicios de que {nombre} puede presentar dislexia. De ser este el caso, el resultado en la evaluación cognitiva de esta prueba verbal estaría sesgado. Por lo que se recomienda para la evaluación cognitiva de {nombre} realizar, en primer lugar, una prueba específica de dislexia. Y para la medición de otras capacidades tales como atención, velocidad de procesamiento o memoria, recurrir a pruebas no verbales.""",
    'P bajo, C alto y PC normal': """ Finalmente, señalar que debe considerarse con cautela esta interpretación de la velocidad de procesamiento y capacidad atencional de {nombre} en base a su rendimiento en las distintas partes de la tarea Stroop. Esto debido a que existen indicios de que {nombre} puede presentar dislexia. De ser este el caso, el resultado en la evaluación cognitiva de esta prueba verbal estaría sesgado. Por lo que se recomienda para la evaluación cognitiva de {nombre} realizar, en primer lugar, una prueba específica de dislexia. Y para la medición de otras capacidades tales como atención, velocidad de procesamiento o memoria, recurrir a pruebas no verbales.""",
    'P bajo, C alto y PC alto': """ Finalmente, señalar que debe considerarse con cautela esta interpretación de la velocidad de procesamiento y capacidad atencional de {nombre} en base a su rendimiento en las distintas partes de la tarea Stroop. Esto debido a que existen indicios de que {nombre} puede presentar dislexia. De ser este el caso, el resultado en la evaluación cognitiva de esta prueba verbal estaría sesgado. Por lo que se recomienda para la evaluación cognitiva de {nombre} realizar, en primer lugar, una prueba específica de dislexia. Y para la medición de otras capacidades tales como atención, velocidad de procesamiento o memoria, recurrir a pruebas no verbales.""",
}

